name: Deploy Next.js to S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build

      - name: Sync to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: out

      - name: Prepare Lambda payload
        run: |
          printf '{"source":"github-actions","status":"deploy-finished"}' > payload.json

      - name: Invoke Lambda after deploy
        run: |
          aws lambda invoke \
            --function-name ${{ secrets.AWS_LAMBDA_FUNCTION }} \
            --region ${{ secrets.AWS_REGION }} \
            --payload file://payload.json \
            response.json

      - name: Show Lambda response
        run: cat response.json
